### PR TITLE
update for timestamp and reversesign.

### PR DESCRIPTION
**Pull request by novica**
Hi Lubos,

This PR fixes (hopefully) the issues noted in [this comment](https://github.com/Manager-io/Localizations.json/pull/3#issuecomment-768212905). I can't test completely though because arch linux is stuck at version 20.9, and my working environment usually is windows.

### CODE REVIEW

**Comment by lubos** [comment]
Thanks, could you please add some sample transactions into this country file as well? Without sample transactions, it's difficult to debug country-specific reports.

**Comment by novica** [comment]
Yes. I will try to do that next week once I am able to work with the latest version of Manager. Currently testing on 20.9.x makes little sense. Can you please merge this so I can update to what seems to be a correct report transformation now?

**Comment by novica** [comment]
BTW, it might be a good idea to have an official cloud access for developing localizations. That way at least we can be sure we are developing on the latest stable Manager version.

**Comment by lubos** [comment]
Looks like lines 141, 142, 143 and 144 do not have comma at the end of the line which makes JSON file invalid. Are you exporting these files from Manager or manually editing them?

**Comment by novica** [comment]
Fixed the commas. Yes. That part I was manually editing and forgot the commas. Like I said, there seem to be different behavior from Manager 20.9.x on Linux and the latest version on Windows, so that's why I am just editing the file directly.

**Pull request merged**
