### PR TITLE
Updating Macedonian.json with sample transactions

### PR DESCRIPTION
**Pull request by novica**
Hi Lubos,

This PR updates the Macedonian localization with sample transactions for every tax code in the system. The file should also contain sample translated account names and codes. As far as I can see the report is generated correctly, except for the due date field which (again) fails to be calculated correctly, although I tried to add an if/else statement. If you can fix that I would be grateful.

Thanks for your help.
Novica

### CODE REVIEW

**Comment by lubos** [comment]
I'm sorry it took so long however new no-coding platform to develop report transformations is now available.

See: https://forum.manager.io/t/report-transformations-no-code-development-platform/35804

This is the way going onwards. I was experimenting with many ideas, also based on your feedback and in the end I settled on what Manager has now.

**Comment by novica** [comment]
Thanks Lubos.

 Does this mean that the report should be reimplemented?

**Comment by lubos** [comment]
Yes. When you import current Macedonian.json, you will need to select on report transformation from drop-down appropriate figures. Labels are already there.

**Comment by novica** [comment]
Aha, no need to redo the work. Thanks.

**Pull request closed without merging**
