### PR TITLE
Create Angola

### PR DESCRIPTION
**Pull request by SHAMSUDDIN-CELL**
Hello, it's the second time it's created because the 1st file disappeared

### CODE REVIEW

**Comment by lubos** [comment]
Isn't official language Portuguese in Angola? Looks like account names are in English

**Comment by SHAMSUDDIN-CELL** [comment]
yes official language is Portuguese,so i need to create in Portuguese?

**Comment by lubos** [comment]
If users in Angola are using accounting software in Portuguese, then everything needs to be in Portuguese.

**Comment by SHAMSUDDIN-CELL** [comment]
so i will update in portuguese

**Comment by SHAMSUDDIN-CELL** [comment]
Only tax code need in Portugese?

**Comment by lubos** [comment]
Tax code is shown on invoices. So it needs to be named the way users in Angola expects it to be named.

**Pull request closed without merging**
