### PR TITLE
Uganda

### PR DESCRIPTION
**Pull request by Lwanga94**

### CODE REVIEW

**Comment by lubos** [comment]
image

- Why code is `UGX001`? Shouldn't that be just `UGX`?
- Why symbol is `Ugx`? Shouldn't that be `USh`?
- Decimal spaces are set to 2. Why? Isn't this currency without subdivision now and therefore decimal spaces should be set to zero?

What's the purpose of these accounts?

image

They don't seem to be linked to any tax code or payslip items.

Also, if you are supplying tax codes, I'd like to see country-specific report using those tax codes. Can you show government form which businesses are lodging to report their tax amounts? We can re-create that in Manager.

**Comment by lubos** [comment]
Please see https://forum.manager.io/t/localizations-new-way-to-contribute/37779

**Comment by Lwanga94** [comment]
I have added another pull request with the right Tax codes for payroll
deductions after the addition of Payroll items.

We prefer using Ugx as opposed to Ush, also their several clients that deal
with foreign currencies and when the exchange rates are done, we shall have
reports with decimals, so I preferred having 2 decimal places for that
reason.

Attached is the VAT Government Tax Returns Sheet that shows the various Tax
Codes I set up.

[image: image.png]

Regards,

**Comment by lubos** [comment]
Please let's continue discussion in this topic:

https://forum.manager.io/t/uganda/37807

**Comment by Lwanga94** [comment]
[image: image.png]

**Pull request closed without merging**
