### PR TITLE
Update Nederland.json

### PR DESCRIPTION
**Pull request by Hennie-Eerhart**
On the forum topic: "Concept BTW Aangifte [decimals and empty 1e]" it was reported that the wrong codes were used. I replaced them by the correct codes, but I'm not a programmer so I hope I enrered the changes in a correct way.

### CODE REVIEW

**Comment by lubos** [comment]
Thanks. Just one question.

image

Why is one figure `Tax on Sales` and the other `Total Sales` ? Shouldn't this be both `Total Sales` ?

**Comment by Hennie-Eerhart** [comment]
Hi Lubos,

 

Apparently a typo from my side.

This is what the codes should be:

 



 

Kind regards and thanks for responding so quick.

 

Hennie Eerhart

Van: Lubos Hasko ***@***.***> 
Verzonden: zaterdag 3 juli 2021 00:01
Aan: Manager-io/Localizations.json ***@***.***>
CC: Hennie-Eerhart ***@***.***>; Author ***@***.***>
Onderwerp: Re: [Manager-io/Localizations.json] Update Nederland.json (#12)

 

Thanks. Just one question.

 <https://user-images.githubusercontent.com/134051/124332407-be77bd00-dbd4-11eb-8179-03570a564552.png> 

Why is one figure Tax on Sales and the other Total Sales ? Shouldn't this be both Total Sales ?

**Comment by lubos** [comment]
Your reply was sent through Github which stripped your images so don't know what it should be. Can you please reply through Github rather than by email? Thanks.

**Comment by Hennie-Eerhart** [comment]
Hi Lubos,
Apparently a typo from my side.
This is the screenshot of what it should be:

image

**Pull request merged**
