### PR TITLE
Update New Zealand.json

### PR DESCRIPTION
**Pull request by dsherman11**
Added a tax code "GST 15% on Imports".  
Removed "GST 0%" and "GST Exempt" from C11.
Added "GST 15% on Imports" to C13, C14, C15.
Added some inspection lines in the table, to clarify contents of C13.

The change to C11 is necessary because the NZ taxation website (ird.govt.nz) has an online form that automatically calculates C12 = C11 * 3/23.  This is because C11 should only include purchases which contain GST 15%.
Also, the NZ GST guide excludes all imported goods from Line 11.  Instead, they should go in Line 13.  This is why another tax code is required.

### CODE REVIEW

**Comment by lubos** [comment]
Thanks for the pull request. Just to give you status on where we stand. I decided to reimplement localizations so these country-specific reports can be created with no coding. I will provide more information in upcoming days.

**Comment by dsherman11** [comment]
Hi Lubos,

That's a good idea.

Just FYI, my pull request might not be entirely accurate.  I recently
checked with our NZ tax authority (IRD) and they say that imported
purchases should be treated as domestic, if the foreign supplier includes
NZ GST in the invoice.  I plan to use this advice, but another NZ
accountant in the thread chooses not to.  I think it's a good solution to
allow users to make their own decisions.

Great product!  How can I contribute?

--zim

**Comment by lubos** [comment]
Check the latest version (21.6.12) in which I'm experimenting with no code approach.

Basically, rather than having Liquid markup in template field, there is now grid which allows you to specify what each cell on the report should contain.

image

It's very verbose but I think learning curve shouldn't be as massive anymore.

**Comment by dsherman11** [comment]
Yes, that's very good!  One feature I like about Liquid is the ability to
have conditionals.  For example, switching between "GST to pay" and "GST
refund".  This might be more difficult in your grid.

I didn't think the learning curve was massive.  The only difficulties were:
1.  Finding out where the form template is stored,
2.  Knowing to use a JSON editor instead of a text editor.

Modifying your code was very straightforward, but I'm a programmer.  Maybe
it's best not to encourage such low-level modification, as some people
might screw it up quite badly.  The new grid system is a good compromise.

--zim

**Comment by lubos** [comment]
Coding gives you the ultimate flexibility but it would be at the cost that only small fraction of users could ever understand what the report is doing.

I will try to give a shot to this no code experiment and see how far I can push it.

**Comment by lubos** [comment]
No-coding platform is now available. Please see:

https://forum.manager.io/t/report-transformations-no-code-development-platform/35804

This is the way going onwards. Have a look at how New Zealand report looks in the latest version. It should be a lot easier to improve it.

**Pull request closed without merging**
