### PR TITLE
Create  northmacedonia.json

### PR DESCRIPTION
**Pull request by novica**
Hi Lubos, 

This is a work in progress file for VAT in North Macedonia as I am trying to convert it from the old to the new system. I run into some issues and maybe you can help me solve them.

<s>Currently when I save this in Manager I get:</s>

<s>Liquid error: Parameter count mismatch. Liquid error: Parameter count mismatch. 
Liquid error: Unable to cast object of type 
'ManagerServer.HttpHandlers.Businesses.Business.Reports.ReportTransformationReports.Transactions'
to type 'System.IConvertible'.  </s>

<s>Liquid error: Number of parameters specified does not match the expected number. 
Liquid error: Number of parameters specified does not match the expected number. 
Liquid error: Specified cast is not valid.</s>

<s>I am not sure where is this coming from. </s>

The other issues I have (which may be related to the one above) are:

* I don't seem to be able to set the due date. I tried some stuff, but no luck. I am trying to do that in line 5-7 of the PR. 
<s>* I don't seem to be able to round the values using `| round`. </s>
* The section about purchases doesn't show the expected values: I am not sure what I am doing wrong here: 

```
{% assign V21 = period | taxcode: DDV_18, DDV_5, tax_exclusive_purchases  | reversesign | round %}
{% assign V22 = period | taxcode: DDV_18, DDV_5, tax_on_purchases | reversesign |  round %}
```

<s>* Summing doesn't work. For example `{% assign V31 = V29 | plus: V30 %}`.</s>
<s>* Accounting basis doesn't show up on the top of the report.</s>
<s>* The XML Save button seems to be broken as well from what it used to be at least.</s>

I am copy/pasting this from the edit form, I actually can't see an option to export it as a file so the table for the report is missing.
I hope you can help. Thanks.

### CODE REVIEW

**Comment by novica** [comment]
OK. Some progress on the due date field. It seems that Manager notation is with a dot on the variables (`due.Date`)? Then, me trying to use that somehow messes things up. So by using `dueDate` I can get the date, almost. Still can't figure out how to have a leading zero on months (eg. 01, 02... ) or if this is the right approach.

**Comment by novica** [comment]
The latest commit (hopefully) fixes some of the other issue. Summing and rounding seem to work again at the expense of drill down possibilities but I think these are not important for this report. 

The download button was broken because of extra white space... who knew?

The due date option doesn't seem to work, although per liquid documentation this should be possible. See: https://www.huratips.com/tech-tips/how-to-add-days-to-date-in-shopify-liquid.html

**Comment by novica** [comment]
Latest commit removes reverse sign form places where it is not needed. 

Apart from the due date calculation, as far as I can see from testing, the only other remaining issue is the calculation of tax exclusive purchases and corresponding taxes.

```
{% assign V21 = period | taxcode: DDV_18, DDV_5, tax_exclusive_purchases   %}
{% assign V22 = period | taxcode: DDV_18, DDV_5, tax_on_purchases   %}
```

doesn’t return just purchases. When I drill down on the fields I can see both sales and purchase invoices. 
Screenshot_20210123_220304


I expect to see only purchases, “Влезна фактура” in my case. Am I doing something wrong here or is this some kind of a bug?

**Comment by lubos** [comment]
Thank you for looking into this.

You will need to submit proper JSON file as what is being submitted does not contain all the information.

To generate JSON, when under `Settings` then `Report Transformations`, click `Export` button in bottom-right corner.

I have updated step-by-step instructions at https://github.com/Manager-io/Localizations.json

As soon as you upload JSON file, I will go through it.

Once again, thank you. You are the first one submitting.

**Comment by novica** [comment]
Hi Lubos, 
Thanks for responding.

When I try to export like that, everything from the demo business gets exported, like account names, reports. Is there a way to export jus the report transformation?

**Comment by lubos** [comment]
That's how it should be. The reason is that report transformation can have dependencies such as accounts, tax codes, custom fields etc. It doesn't work in isolation.

The reason why transactions are exported as well is because they serve as testing data.

If you are building report transformation within your real business, then obviously you can't submit that. You need to create empty business, set it up with everything that is needed + testing transactions.

**Comment by novica** [comment]
OK. There is the full json file. I haven't localized anything else as I was just looking to the the VAT report. But I guess other things may be added ones this is officially there.

**Comment by lubos** [comment]
Excellent work.

Two points:

1. Try not to use `balance` filter when showing figures on the report. The reason is that `balance` filter will turn hyperlink into non-clickable amount. We want to preserve ability to drill-down to individual transactions even from country-specific reports. This is to ensure that users can see how the figure ended up being calculated. Seeing figure `1,000` does not give much assurance that software is doing the right thing but if the user can click on `1,000` figure and see list of transactions which made up this total, that will be a lot better. Not everything needs to be clickable. For example, if we have total figures such as V20 which are sum of previously shown figures, then that doesn't have to be clickable.
2. Testing data needs to be created. Sample transactions which are abusing every angle.

Other than that. I'm very impressed. I wonder what feedback you can give on overall experience of building these country-specific reports and what I can do at my end to improve the experience.

**Comment by novica** [comment]
Regarding 1. I am using balance because  I needed to round the numbers. The report shouldn't have any decimals, and this is the solution I realized was possible. I am okay to changing that if there is another approach. Regarding 2. OK I guess I can add couple of invoices to show the data. But my question is will all that get imported when creating a new business or updating an old one? 

The overall experience was pretty cumbersome to be honest. There is not enough documentation. I had to ping Patch on the forum few times to get a better understating of the things. There were other hiccups as well, for example it's strange that there is `add_years` but not `add_days` option in the `luquid` code. The whole excel-like form builder is really difficult to work with, no button, right click for everything, and no copy/pasting between companies that will include the applied styles.

**Comment by lubos** [comment]
> I am using balance because I needed to round the numbers

My view on this is not to round them within the report. Maybe I can make it an option to show rounded figures for any report within Manager. So no need to round these figures.

> will all that get imported when creating a new business or updating an old one

No. Manager cherry-picks from the entire JSON file only relevant info when importing country-specific report. It will figure out what tax codes, accounts or custom fields are required for the report and imports just that.

> The whole excel-like form builder is really difficult to work with, no button, right click for everything, and no copy/pasting between companies that will include the applied styles.

This is my concern too. I think it's still early to tell whether spreadsheet editor should be scrapped and go code only.

**Comment by lubos** [comment]
Have a look at the latest version (21.1.49). It now includes your report.

**Comment by novica** [comment]
Hi Lubos, 

I finally updated on my working machine. Two issues here: 

First it seems that the second part of the report beginning with `"ВЛЕЗНИ ИСПОЛНУВАЊА СО ПРАВО НА ОДБИВКА"` has negative numbers on windows, but positive on linux? Is this possible? I was developing the report transformation on linux and on a somewhat older version of Manager. Could it be that there are changes in how these things are handled?  Should I just make another PR with `reversesign` on the affected fields?

And two, the due date calculation throws an error with `Liquid error: Year, Month, and Day parameters describe an un-representable DateTime.` I am thinking this is happening only on reports where the due date is in the next year, so for a period of 1 October 2020 to 31 December 2020 the due date is 25 January 2021 and the error is shown. No error when the period is say 1 July to 30 September with a due date of 25 October 2020. So, my question here is can you suggest a better way to calculate the due date on the report, so that it works for any period?

**Pull request merged**
