### PR TITLE
Angola.json

### PR DESCRIPTION
**Pull request by SHAMSUDDIN-CELL**
Text Angola.JSON

### CODE REVIEW

**Comment by lubos** [comment]
Thanks for your contribution. One question before merge.

How did you come up with layout for report transformation?

What do you actually need to lodge in Angola. Do you have a screenshot of the form for Angola tax lodgement?

**Comment by SHAMSUDDIN-CELL** [comment]
Thank you very much Mr.Lubos,
here is link about tax departments of Angola
https://www.agt.minfin.gov.ao/PortalAGT/#!/servicos-fiscais//impostos

**Comment by lubos** [comment]
The link is general information about VAT.

What form do you actually have to lodge? The report transformation should reassamble the form that you need to lodge as close as possible.

**Comment by SHAMSUDDIN-CELL** [comment]
Thanks, I'll check it out.

**Comment by SHAMSUDDIN-CELL** [comment]
Dear Lubos, sorry for the late reply, but I don't understand you well, can
you explain what you really need to end this problem

**Comment by lubos** [comment]
Do you have PDF or screenshot of actual tax lodgement form for which this report transformation is created?

**Comment by SHAMSUDDIN-CELL** [comment]
Dear Lubos,pls find attached doc

**Comment by lubos** [comment]
Can you attach it here on Github rather than attaching to email? Github strips attachment so I can't see it. Thanks.

**Comment by SHAMSUDDIN-CELL** [comment]
means I need Angola.json attached to GitHub ?

**Comment by lubos** [comment]
Please do not reply through email. When you get email, click "view it on GitHub" link at the bottom and reply on Github.

I need to see lodgement form. What form do you fill in to lodge tax figures.

**Comment by SHAMSUDDIN-CELL** [comment]
[modelos-formularios_editaveis_imposto-predial-urbano-ipu_imposto-predial-urbano-anexo-1-da-declaracao-modelo-5.pdf](https://github.com/Manager-io/Localizations.json/files/6776307/modelos-formularios_editaveis_imposto-predial-urbano-ipu_imposto-predial-urbano-anexo-1-da-declaracao-modelo-5.pdf)
[modelos-formularios_editaveis_imposto-predial-urbano-ipu_imposto-predial-urbano-declaracao-modelo-5.pdf](https://github.com/Manager-io/Localizations.json/files/6776308/modelos-formularios_editaveis_imposto-predial-urbano-ipu_imposto-predial-urbano-declaracao-modelo-5.pdf)

**Comment by lubos** [comment]
I think there is some major misunderstanding...

You've created this report transformation:

image

What do you do with these figures? How do you lodge them? Is there a form from your tax authority where you copy these figures to? Can see that form?

**Comment by SHAMSUDDIN-CELL** [comment]
Sorry, this is my error creating the transformation report which was copied from Newzeland Gst format. Can I send without code?

**Comment by lubos** [comment]
Send what you can.

**Comment by SHAMSUDDIN-CELL** [comment]
Dear Lubos, after a long time I need to know what information you really
need from me to complete this situation, as I am not an Accountant so you
can explain better, I usually need to create a tax code and QR code for
Angola Country otherwise in resource i will think later

**Comment by SHAMSUDDIN-CELL** [comment]
[modelos-formularios_editaveis_imposto-industrial-ii_imposto-industrial-declaracao-modelo-1_v2.pdf](https://github.com/Manager-io/Localizations.json/files/7345689/modelos-formularios_editaveis_imposto-industrial-ii_imposto-industrial-declaracao-modelo-1_v2.pdf)
[modelos-formularios_editaveis_imposto-sobre-os-rendimentos-do-trabalho-irt_irt-anual-modelo-2-grupo-a.pdf](https://github.com/Manager-io/Localizations.json/files/7345692/modelos-formularios_editaveis_imposto-sobre-os-rendimentos-do-trabalho-irt_irt-anual-modelo-2-grupo-a.pdf)
[modelos-formularios_editaveis_imposto-predial-urbano-ipu_imposto-predial-urbano-declaracao-modelo-5.pdf](https://github.com/Manager-io/Localizations.json/files/7345693/modelos-formularios_editaveis_imposto-predial-urbano-ipu_imposto-predial-urbano-declaracao-modelo-5.pdf)
[modelos-formularios_editaveis_imposto-de-selo-is_imposto-de-selo.pdf](https://github.com/Manager-io/Localizations.json/files/7345694/modelos-formularios_editaveis_imposto-de-selo-is_imposto-de-selo.pdf)

**Comment by lubos** [comment]
I'm closing this pull request.

Please have a look at https://forum.manager.io/t/contribute-new-country-template/37706

**Pull request closed without merging**
