### PR TITLE
Uganda

### PR DESCRIPTION
**Pull request by Lwanga94**

### CODE REVIEW

**Comment by lubos** [comment]
Please no more pull requests. See https://forum.manager.io/t/localizations-new-way-to-contribute/37779 for alternative.

**Comment by Lwanga94** [comment]
But am unable to create Uganda, and Uganda is not listed among those I see.

[image: image.png]

**Comment by lubos** [comment]
Uganda added

**Comment by Lwanga94** [comment]
Awesome, thanks!

Now can I know when we are able to integrate Manager with Uganda Revenue
Authority's EFRIS system as earlier discussed?

**Pull request closed without merging**
